-- =================================================================
-- LA WEB CORE — Railway Bootstrap Part 1 of 5
-- Extensions + Auth stub + All Enums
-- Run in Railway Query Editor FIRST
-- =================================================================
-- Idempotent: uses DO $$ blocks for types (won't fail if already exist)

CREATE SCHEMA IF NOT EXISTS extensions;
CREATE SCHEMA IF NOT EXISTS auth;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "pgcrypto" SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "pg_trgm" SCHEMA extensions;

DO $$
BEGIN
    CREATE EXTENSION IF NOT EXISTS "vector" SCHEMA extensions;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'pgvector not available — AI/RAG features disabled';
END $$;

GRANT USAGE ON SCHEMA extensions TO PUBLIC;
GRANT ALL ON SCHEMA extensions TO postgres;

-- Auth stub (satisfies FK references from users table)
CREATE TABLE IF NOT EXISTS auth.users (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email       TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION auth.uid() RETURNS UUID
    LANGUAGE sql STABLE
    RETURN COALESCE(
        NULLIF(current_setting('request.jwt.claim.sub', true), '')::UUID,
        '00000000-0000-0000-0000-000000000000'::UUID
    );

-- Enums (all wrapped in DO $$ so re-run is safe)
DO $$ BEGIN CREATE TYPE user_status AS ENUM ('active','invited','suspended','deactivated'); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE campaign_status AS ENUM ('BRIEF','CONTACTANDO','PLAN_DE_CUENTAS','PULL','CAMPAÑA_INTERNA','REPORTE','TERMINADA','CANCELADA','PAUSADA'); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE campaign_objective AS ENUM ('AWARENESS','CONSIDERACION','CONVERSION','GESTION_DE_CRISIS','BRANDING','LANZAMIENTO','RETENCION'); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE influencer_tier AS ENUM ('NANO','MICRO','MID','MACRO','MEGA','MIX'); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE campaign_influencer_status AS ENUM ('PROPUESTO','CONTACTADO','CONFIRMADO','CONTRATADO','CONTENIDO_ENTREGADO','PAGADO','RECHAZADO','CANCELADO'); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE campaign_link_type AS ENUM ('BRIEF','DOCUMENTO_INDUCCION','CONTRATO','HOOK','AUTOMATIZACION','FORMULARIO','PULL','PLAN_DE_CUENTAS','CAMPANA_INTERNA','DRIVE','REPORTE','CANVA','TRELLO','HYPEAUDITOR','OTRO'); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE kpi_category AS ENUM ('ALCANCE','ENGAGEMENT','CONVERSION','RETENCION','AWARENESS','SENTIMIENTO','BRAND_HEALTH'); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE kpi_source AS ENUM ('MANUAL','HYPEAUDITOR','PLATAFORMA_NATIVA','FORMULARIO','IMPORTADO','IA'); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE task_status AS ENUM ('PENDIENTE','EN_PROGRESO','BLOQUEADA','COMPLETADA','CANCELADA'); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE task_priority AS ENUM ('BAJA','MEDIA','ALTA','URGENTE'); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE integration_provider AS ENUM ('HYPEAUDITOR','CANVA','GOOGLE_DRIVE','TRELLO','SLACK','META','TIKTOK','YOUTUBE','OPENAI','ANTHROPIC'); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE ai_job_status AS ENUM ('PENDING','RUNNING','COMPLETED','FAILED','CANCELLED'); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE ai_job_type AS ENUM ('EMBEDDING','RAG_QUERY','BRIEF_GENERATION','POST_MORTEM_GENERATION','INSIGHT_GENERATION','FORECAST','MATCHMAKING','SENTIMENT_ANALYSIS'); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE audit_action AS ENUM ('CREATE','UPDATE','DELETE','RESTORE','LOGIN','LOGOUT','EXPORT','IMPORT','STATUS_CHANGE','PERMISSION_CHANGE','ROLE_CHANGE'); EXCEPTION WHEN OTHERS THEN NULL; END $$;
